# Generated by Django 4.0.2 on 2022-02-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='occupation',
            field=models.IntegerField(choices=[(1, 'manager'), (2, 'junior specialist'), (3, 'specialist'), (4, 'senior specialist'), (5, 'consultant'), (6, 'assistant')]),
        ),
    ]
